services:
  backend:
    build: .
    entrypoint: /app/entrypoint.sh
    container_name: NS_backend
    ports:
      - "8000:8000"
    volumes:
      - ./alembic:/app/alembic
    env_file:
      - environment/.env
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:17
    container_name: NS_postgres_db
    ports:
      - "5432:5432"
    env_file:
      - environment/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: NS_redis
    ports:
      - "6379:6379"
    env_file:
      - environment/.env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-redispassw}" ]

  celery_worker:
    build: .
    command: poetry run celery -A celery_app worker -P solo --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - environment/.env

  celery_beat:
    build: .
    command: poetry run celery -A celery_app.app beat --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - environment/.env

volumes:
  postgres_data:
