exclude = [
    "alembic/versions/*",
]

line-length = 120

[lint]
select = [
    "E",   # PEP8 ошибки (например, отступы)
    "F",   # Pyflakes (неиспользуемый код)
    "W",   # Предупреждения
    "I",   # Сортировка импортов
    "UP",  # Современный Python (например, Union -> |)
]

fixable = ["ALL"]

[format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 120